zone:
  name: sc-1
server:
  port: 8081
eureka:
  instance:
    metadata-map:
      zone: sc
    hostname: localhost
  client:
    region: chongqing
    availability-zones:
      chongqing: sc,tc,zb
    service-url:
      sc: http://eureka-sc:8761/eureka/
      tc: http://eureka-tc:8762/eureka/
      zb: http://eureka-zb:8763/eureka/